import {Cairo} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const cairo = Cairo({subsets: ["latin"],weight: ['300','400','500','600','700']});

export const metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (<html lang="en">
        <body className={cairo.className}><NavBar/>{children}<Footer/></body>
        </html>);
}
