import { Cairo } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "@/components/ui/toaster";
import { getDictionary } from "@/app/[lang]/dictionaries";

const cairo = Cairo({ subsets: ["latin"], weight: ['300', '400', '500', '600', '700'] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { lang } }) {
        const dict = await getDictionary(lang);
    return (
        <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"}>
        <body className={cairo.className}>
            <NavBar lang={lang} dict={dict} />
            {children}
            <Footer dict={dict} />
            <Toaster />
        </body>
        </html>
    );
}
